import { DarkTheme, DefaultTheme, useTheme as useThemeBase } from '@react-navigation/native';
import { Appearance } from 'react-native';

export const BlueDefaultTheme = {
  ...DefaultTheme,
  closeImage: require('../img/close.png'),
  barStyle: 'dark-content',
  scanImage: require('../img/scan.png'),
  colors: {
    ...DefaultTheme.colors,
    borderWidth: 0.5,
    backgroundPrimary: '#F7F8FA',
    backgroundSurface: '#FFFFFF',
    backgroundSurfaceSecondary: '#F0F2F6',
    textPrimary: '#111317',
    textSecondary: '#4F5663',
    textDisabled: '#8A919E',
    borderSubtle: '#E6E8EE',
    borderDefault: '#CBD1DB',
    accentPrimary: '#055B69',
    accentSuccessText: '#1F9D55',
    accentSuccessBackground: '#D5F9E0',
    accentErrorText: '#C60001',
    accentErrorBackground: '#FFE3E3',
    accentInfoText: '#055B69',
    accentInfoBackground: '#E7F3F5',
    brandingColor: '#FFFFFF',
    customHeader: '#FFFFFF',
    foregroundColor: '#111317',
    borderTopColor: '#E6E8EE',
    buttonBackgroundColor: '#F0F2F6',
    buttonTextColor: '#111317',
    secondButtonTextColor: '#4F5663',
    buttonAlternativeTextColor: '#111317',
    buttonDisabledBackgroundColor: '#E6E8EE',
    buttonDisabledTextColor: '#8A919E',
    inputBorderColor: '#CBD1DB',
    inputBackgroundColor: '#FFFFFF',
    alternativeTextColor: '#4F5663',
    alternativeTextColor2: '#055B69',
    buttonBlueBackgroundColor: '#CBD1DB',
    buttonGrayBackgroundColor: '#E6E8EE',
    incomingBackgroundColor: '#D5F9E0',
    incomingForegroundColor: '#1F9D55',
    outgoingBackgroundColor: '#FFE3E3',
    outgoingForegroundColor: '#C60001',
    successColor: '#1F9D55',
    failedColor: '#C60001',
    placeholderTextColor: '#8A919E',
    shadowColor: '#111317',
    inverseForegroundColor: '#FFFFFF',
    hdborderColor: '#055B69',
    hdbackgroundColor: '#E7F3F5',
    lnborderColor: '#055B69',
    lnbackgroundColor: '#E7F3F5',
    background: '#F7F8FA',
    lightButton: '#FFFFFF',
    ballReceive: '#D5F9E0',
    ballOutgoing: '#FFE3E3',
    lightBorder: '#E6E8EE',
    ballOutgoingExpired: '#F0F2F6',
    modal: '#FFFFFF',
    formBorder: '#CBD1DB',
    modalButton: '#CBD1DB',
    darkGray: '#4F5663',
    scanLabel: '#055B69',
    feeText: '#4F5663',
    feeLabel: '#D5F9E0',
    feeValue: '#055B69',
    feeActive: '#D5F9E0',
    labelText: '#4F5663',
    cta2: '#055B69',
    outputValue: '#111317',
    elevated: '#FFFFFF',
    mainColor: '#F0F2F6',
    success: '#D5F9E0',
    successCheck: '#1F9D55',
    msSuccessBG: '#1F9D55',
    msSuccessCheck: '#111317',
    newBlue: '#055B69',
    redBG: '#FFE3E3',
    redText: '#C60001',
    changeBackground: '#E7F3F5',
    changeText: '#055B69',
    receiveBackground: '#D5F9E0',
    receiveText: '#1F9D55',
    androidRippleColor: '#CBD1DB',
  },
};

export type Theme = typeof BlueDefaultTheme;

export const BlueDarkTheme: Theme = {
  ...DarkTheme,
  closeImage: require('../img/close-white.png'),
  scanImage: require('../img/scan-white.png'),
  barStyle: 'light-content',
  colors: {
    ...BlueDefaultTheme.colors,
    ...DarkTheme.colors,
    backgroundPrimary: '#09090B',
    backgroundSurface: '#141418',
    backgroundSurfaceSecondary: '#1C1F26',
    textPrimary: '#F3F4F6',
    textSecondary: '#A0A6B2',
    textDisabled: '#6B7280',
    borderSubtle: '#2A2E36',
    borderDefault: '#3A3F48',
    accentPrimary: '#1F7F8E',
    accentSuccessText: '#47E86A',
    accentSuccessBackground: '#1E3A2A',
    accentErrorText: '#FF6B6B',
    accentErrorBackground: '#3A1A1A',
    accentInfoText: '#2A93A2',
    accentInfoBackground: '#12353D',
    customHeader: '#09090B',
    brandingColor: '#09090B',
    borderTopColor: '#2A2E36',
    background: '#09090B',
    foregroundColor: '#F3F4F6',
    secondButtonTextColor: '#A0A6B2',
    buttonDisabledBackgroundColor: '#2A2E36',
    buttonDisabledTextColor: '#6B7280',
    buttonBackgroundColor: '#1C1F26',
    buttonTextColor: '#F3F4F6',
    lightButton: '#141418',
    buttonAlternativeTextColor: '#F3F4F6',
    alternativeTextColor: '#A0A6B2',
    alternativeTextColor2: '#1F7F8E',
    inputBorderColor: '#3A3F48',
    placeholderTextColor: '#6B7280',
    incomingBackgroundColor: '#1E3A2A',
    incomingForegroundColor: '#47E86A',
    outgoingBackgroundColor: '#3A1A1A',
    outgoingForegroundColor: '#FF6B6B',
    successColor: '#47E86A',
    failedColor: '#FF6B6B',
    hdborderColor: '#2A93A2',
    hdbackgroundColor: '#12353D',
    lnborderColor: '#2A93A2',
    lnbackgroundColor: '#12353D',
    ballReceive: '#1E3A2A',
    ballOutgoing: '#3A1A1A',
    lightBorder: '#2A2E36',
    ballOutgoingExpired: '#1C1F26',
    modal: '#141418',
    formBorder: '#3A3F48',
    inputBackgroundColor: '#141418',
    modalButton: '#3A3F48',
    darkGray: '#A0A6B2',
    feeText: '#A0A6B2',
    feeLabel: '#1E3A2A',
    feeValue: '#F3F4F6',
    feeActive: '#1E3A2A',
    cta2: '#1F7F8E',
    outputValue: '#F3F4F6',
    elevated: '#141418',
    mainColor: '#1C1F26',
    success: '#1E3A2A',
    successCheck: '#47E86A',
    buttonBlueBackgroundColor: '#3A3F48',
    scanLabel: '#1F7F8E',
    labelText: '#F3F4F6',
    msSuccessBG: '#47E86A',
    msSuccessCheck: '#09090B',
    newBlue: '#2A93A2',
    redBG: '#3A1A1A',
    redText: '#FF6B6B',
    changeBackground: '#12353D',
    changeText: '#2A93A2',
    receiveBackground: '#1E3A2A',
    receiveText: '#47E86A',
    androidRippleColor: '#2A2E36',
  },
};

// Casting theme value to get autocompletion
export const useTheme = (): Theme => useThemeBase() as Theme;

export const platformColors = {
  background: BlueDefaultTheme.colors.background,
  card: BlueDefaultTheme.colors.modal ?? BlueDefaultTheme.colors.elevated ?? BlueDefaultTheme.colors.background,
  text: BlueDefaultTheme.colors.foregroundColor,
  secondaryText: BlueDefaultTheme.colors.alternativeTextColor ?? BlueDefaultTheme.colors.darkGray,
  separator: BlueDefaultTheme.colors.lightBorder ?? BlueDefaultTheme.colors.borderTopColor,
  chevron: BlueDefaultTheme.colors.alternativeTextColor ?? BlueDefaultTheme.colors.darkGray,
};

export class BlueCurrentTheme {
  static colors: Theme['colors'];
  static closeImage: Theme['closeImage'];
  static scanImage: Theme['scanImage'];

  static updateColorScheme(): void {
    const isColorSchemeDark = Appearance.getColorScheme() === 'dark';
    BlueCurrentTheme.colors = isColorSchemeDark ? BlueDarkTheme.colors : BlueDefaultTheme.colors;
    BlueCurrentTheme.closeImage = isColorSchemeDark ? BlueDarkTheme.closeImage : BlueDefaultTheme.closeImage;
    BlueCurrentTheme.scanImage = isColorSchemeDark ? BlueDarkTheme.scanImage : BlueDefaultTheme.scanImage;
    const colors = BlueCurrentTheme.colors;
    platformColors.background = colors.background;
    platformColors.card = colors.modal ?? colors.elevated ?? colors.background;
    platformColors.text = colors.foregroundColor;
    platformColors.secondaryText = colors.alternativeTextColor ?? colors.darkGray;
    platformColors.separator = colors.lightBorder ?? colors.borderTopColor;
    platformColors.chevron = colors.alternativeTextColor ?? colors.darkGray;
  }
}

BlueCurrentTheme.updateColorScheme();
